### ISSUE TITLE
Doc webpage is broken

### ISSUE THREAD

**Issue by magom001** [Telegram-Mini-Apps/init-data-golang#3]
https://docs.twa.dev/docs/libraries/init-data-golang
<img width="845" alt="Screenshot 2023-10-28 at 22 08 15" src="https://github.com/Telegram-Mini-Apps/init-data-golang/assets/2744275/9ba07d51-7b8b-47ba-a7aa-e5b629dd5bcc">

**Comment by heyqbnk** [comment]
Yeah, sorry. Documentation is currently moving to another domain. You can find needed docs here:
https://docs.telegram-mini-apps.com/docs/libraries/init-data-golang

I will update docs visual representation and content in the next few days. Package README was updated, thank you!
