### ISSUE TITLE
ge get error

### ISSUE THREAD

**Issue by chenyu1990** [Telegram-Mini-Apps/init-data-golang#5]
`go: github.com/telegram-mini-apps/init-data-golang@v1.1.1: parsing go.mod:
        module declares its path as: github.com/Telegram-Web-Apps/init-data-golang
                but was required as: github.com/telegram-mini-apps/init-data-golang
`

go version: 1.18 darwin/arm64

**Comment by heyqbnk** [comment]
Yeah, seems like a bug. I forgot to update module name when changing the GitHub organization name.

Will be fixed during this day. Thank you for the report!

**Comment by heyqbnk** [comment]
Fixed in v1.1.2
